#if !canImport(ObjectiveC)
import XCTest

extension BitReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitReaderTests = [
        ("testBitReader", testBitReader),
        ("testBitReaderCount", testBitReaderCount),
    ]
}

extension BlockTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BlockTypeTests = [
        ("testBlockType", testBlockType),
    ]
}

extension CRC32Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CRC32Tests = [
        ("testCRC32", testCRC32),
        ("testCRC32Fox", testCRC32Fox),
        ("testCRC32Stream", testCRC32Stream),
        ("testCRC32Zero", testCRC32Zero),
    ]
}

extension GZipTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GZipTests = [
        ("testDecode", testDecode),
    ]
}

extension HuffmanBinaryHeapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HuffmanBinaryHeapTests = [
        ("testHeapFromRange", testHeapFromRange),
        ("testHeapFromValues", testHeapFromValues),
        ("testRead", testRead),
    ]
}

extension InflateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InflateTests = [
        ("testInflateDynamicHuffman", testInflateDynamicHuffman),
        ("testInflateFixedHuffman", testInflateFixedHuffman),
        ("testInflateNoCompression", testInflateNoCompression),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BitReaderTests.__allTests__BitReaderTests),
        testCase(BlockTypeTests.__allTests__BlockTypeTests),
        testCase(CRC32Tests.__allTests__CRC32Tests),
        testCase(GZipTests.__allTests__GZipTests),
        testCase(HuffmanBinaryHeapTests.__allTests__HuffmanBinaryHeapTests),
        testCase(InflateTests.__allTests__InflateTests),
    ]
}
#endif
